name: Stamp DevAssist CMDT

on:
  workflow_call:
    inputs:
      filePath:
        required: true
        type: string
      repoName:
        required: true
        type: string
      commitSha:
        required: true
        type: string
      isProduction:
        required: true
        type: boolean
    secrets:
      SF_USERNAME:
        required: true
      SF_JWT_KEY:
        required: true
      SF_CLIENT_ID:
        required: true

jobs:
  stamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions repo
        uses: actions/checkout@v4

      - name: Set up SFDX
        uses: salesforcecli/github-action@v1

      - name: Authenticate to target org
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          sf org login jwt \
            --client-id ${{ secrets.SF_CLIENT_ID }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --alias target-org

      - name: Call Apex to stamp CMDT
        run: |
          sf apex run --alias target-org --json --loglevel fatal --code "
            MetadataRepoStampController.stampMetadataRecord(
              '$(basename ${{ inputs.filePath }})', 
              'LWC', 
              '${{ inputs.filePath }}',
              'your-org-owner', 
              '${{ inputs.repoName }}',
              '${{ inputs.commitSha }}',
              'https://github.com/your-org-owner/${{ inputs.repoName }}/blob/main/${{ inputs.filePath }}',
              'N/A', 
              'GitHub Action', 
              '${{ secrets.SF_USERNAME }}',
              ${{ inputs.isProduction }}
            );
          "